ua:
  active_games:
    - com-fungames-battleroyale
    - com-wildlife-games-battle-royale-free-zooba
    - com-fungames-sniper3d
    - com-wildlifestudios-suspects
    - com-wildlifestudios-free-online-games-suspects
    - com-fungames-battletanksbeta
    - com-wildlifestudios-skywarriors
    - com-wildlifestudios-jet-airplane-games-sky-warriors
    - com-fungames-tennisclash
    - com-tfgco-games-sports-free-tennis-clash
    - com-fungames-colorbynumber
    - com-tfgco-apps-coloring-free-color-by-number
    - com-fungames-blockcraft
