topaz_installs: "production.events"
http_installs: "marta_dev.http_installs"
attributed_installs: "marta_dev.attributed_installs"
updated_attributions: "marta_dev.updated_attributions"
clicks: "marta_dev.clicks"
impressions: "production.impressions"
