#
marta:
  inputs:
    topaz_installs: {{topaz_installs}}
    http_installs: {{http_installs}}
    attributed_installs: {{attributed_installs}}
    updated_attributions: {{updated_attributions}}
    clicks: {{clicks}}
    impressions: {{impressions}}
  outputs:
    attributed_installs: {{attributed_installs}}
