#
marta:
  inputs:
    topaz_installs: {{marta.topaz_installs}}
    http_installs: {{marta.http_installs}}
    attributed_installs: {{marta.attributed_installs}}
    updated_attributions: {{marta.updated_attributions}}
    clicks: {{marta.clicks}}
    impressions: {{marta.impressions}}
  outputs:
    attributed_installs: {{marta.attributed_installs}}
